Russian translation
Ridderrasmus/RPVoiceChat pull request #86
Opened 2023-10-03 21:18 UTC by Nyuhnyash

2023-10-05 04:03 UTC, Dmitry221060 requested changes
Hello, thank you for your contribution!
Overall translations look good, but I left few suggestions to improve them. You can accept them, propose alternative or comment on why do you think your version would fit better.
Also feel free to add yourself into contributors list in `modinfo.json` ^^

2023-10-06 12:00 UTC, Nyuhnyash commented on assets/rpvoicechat/lang/ru.json
> +    "item-telegraphwire": "Телеграфный провод",
В моде нет телеграфа, значит, и провода от него быть не должно, а "телеграфный" это характеристка                                            провода, не обязательно его принадлежность к телеграфу.

2023-10-06 12:05 UTC, Nyuhnyash commented on assets/rpvoicechat/lang/ru.json
> +    "block-callbell": "Вызывной звонок",
```suggestion
    "block-callbell": "Звонок",
```

2023-10-06 12:17 UTC, Nyuhnyash commented on assets/rpvoicechat/lang/ru.json
> +    "Gui.ModMenu.Tab.AudioOutput": "Аудиовыход",
```suggestion
    "Gui.ModMenu.Tab.AudioInput": "Устройство ввода звука",
    "Gui.ModMenu.Tab.AudioOutput": "Устройство вывода звука",
```
or
```suggestion
    "Gui.ModMenu.Tab.AudioInput": "Входное аудиоустройство",
    "Gui.ModMenu.Tab.AudioOutput": "Выходное аудиоустройство",
```

2023-10-06 12:30 UTC, Nyuhnyash commented on assets/rpvoicechat/lang/ru.json
> +    "Gui.ModMenu.loopback.Tooltip": "Проигрывать записываемый звук в аудиовыход",
Tooltip is meant to make clear the checkbox purpose.
```suggestion
    "Gui.ModMenu.loopback.Tooltip": "Проигрывать записываемый звук в выходное аудиоустойство",
```

2023-10-06 17:23 UTC, Dmitry221060 commented on assets/rpvoicechat/lang/ru.json
> +    "item-telegraphwire": "Телеграфный провод",
"Телеграфный провод" sounds unnatural/incorrect but alright

2023-10-06 17:24 UTC, Dmitry221060 commented on assets/rpvoicechat/lang/ru.json
> +    "block-callbell": "Вызывной звонок",
Yeah, sounds good to me. 👍

2023-10-06 17:27 UTC, Dmitry221060 commented on assets/rpvoicechat/lang/ru.json
> +    "Gui.ModMenu.Tab.AudioOutput": "Аудиовыход",
AudioInput tab is intended for settings related to recording audio, it is more about audio than about some device
Same with AudioOutput. Also it is preferable that tab names are short and simple for them to look better in the UI and not take too much screen space

2023-10-06 17:29 UTC, Dmitry221060 commented on assets/rpvoicechat/lang/ru.json
> +    "Gui.ModMenu.loopback.Tooltip": "Проигрывать записываемый звук в аудиовыход",
I'm fine with either of commented alternatives 👍

2023-10-06 17:30 UTC, Dmitry221060 requested changes
Still unhappy with tab names

2023-10-07 10:12 UTC, Nyuhnyash commented on assets/rpvoicechat/lang/ru.json
> +    "Gui.ModMenu.Tab.AudioOutput": "Аудиовыход",
You're right. I'm sorry, I mistook with other line

2023-10-07 10:21 UTC, Nyuhnyash commented on assets/rpvoicechat/lang/ru.json
> +    "item-telegraphwire": "Телеграфный провод",
"[Телеграфный провод](https://context.reverso.net/translation/english-russian/telegraph+wire)" has lots more uses than suggested variant

2023-10-07 10:27 UTC, Nyuhnyash commented on assets/rpvoicechat/lang/ru.json
> +    "Gui.ModMenu.Tab.AudioOutput": "Аудиовыход",
```suggestion
    "Gui.ModMenu.Tab.AudioInput": "Входное аудио",
    "Gui.ModMenu.Tab.AudioOutput": "Исходящее аудио",
```

2023-10-07 10:46 UTC, Dmitry221060 approved these changes
Tested in game, looks great 👍 

Merge with squash.

2023-10-07 13:26 UTC, merged